#xrandr --output DP-0 --off --output DP-1 --off --output HDMI-0 --mode 2560x1440 --pos 2560x0 --rotate normal --output DP-2 --off --output DP-3 --off --output DP-4 --mode 2560x1440 --pos 0x0 --rotate normal --output DP-5 --off --output USB-C-0 --off
~/.fehbg &
xmodmap ~/.Xmodmap
export QT_QPA_PLATFORMTHEME="qt5ct"
#export XDG_CURRENT_DESKTOP="KDE"
export GTK_IM_MODULE=ibus
#export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
exec i3
export GTK_IM_MODULE=ibus
#export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus


